### ISSUE TITLE
Bot crashes when reading an embed.

### ISSUE THREAD

**Issue by whitman-colm** [skilstak/discord-public#1]
When an embed without any other content is posted (like a gh update), the bot decides it would be a very nice time to crash. Why does it do this (my guess is that somewhere something is trying to forcefully typecast it as a string)? And more importantly how can this be fixed? Note the crash seems to be thrown in `./src/commandHandler/module.go:36` AKA the call to the `canTriggerBot()` method.

![screen shot 2018-01-23 at 17 43 43 -05 00](https://user-images.githubusercontent.com/7927596/35304893-4c332dc2-0065-11e8-8669-6129f0e8c806.png)

**Comment by gabeart10** [comment]
Fixed in https://github.com/skilstak/discord-public/commit/f6fb47cc5af595bfbecb89f787e374fb6d85fd10
