### ISSUE TITLE
Add Command Flags

### ISSUE THREAD

**Issue by whitman-colm** [skilstak/discord-public#3]
The bot should be able to cleverly parse command flags like `--name John Smith` and `-v`. This would allow for more intricate commands and for each command to have a --help/-h option.

Example:

```
John  (21:00): >help --command ping
MyBot (21:00): Here's the detailed info for the `ping` command 
[...]
Jane  (21:03): >help --message
MyBot (21:04): Ok! I've sent you a DM with help info.
```

This will probably require some very clever parsing and might be best if it had its own module. I haven't done much parsing and I'm just throwing ideas around.

**Comment by gabeart10** [comment]
Would it be necessary to differentiate b/w a `--` and `-`?
So, would I need to output just []string or two different []string for each type of flag?

**Comment by whitman-colm** [comment]
I'm thinking `-` for modifiers (like how `-v` is verbose) and `--` for longer values (`--name John`).

**Comment by gabeart10** [comment]
Added the parser in https://github.com/skilstak/discord-public/commit/2ffcfee26e35761a94dbe68159b25bbcbe666402
